hl.curve("nothingEase", { type = "bezier", points = { {0.2, 0.0}, {0.0, 1.0} } })
hl.curve("nothingFade", { type = "bezier", points = { {0.4, 0.0}, {0.1, 1.0} } })

hl.animation({ leaf = "global",           enabled = true, speed = 4,  bezier = "nothingFade" })
hl.animation({ leaf = "windows",          enabled = true, speed = 4,  bezier = "nothingEase", style = "slide" })
hl.animation({ leaf = "windowsOut",       enabled = true, speed = 4,  bezier = "nothingEase", style = "slide" })
hl.animation({ leaf = "windowsMove",      enabled = true, speed = 4,  bezier = "nothingEase" })
hl.animation({ leaf = "border",           enabled = true, speed = 4,  bezier = "nothingEase" })
hl.animation({ leaf = "fade",             enabled = true, speed = 4,  bezier = "nothingFade" })
hl.animation({ leaf = "fadeDim",          enabled = true, speed = 4,  bezier = "nothingFade" })
hl.animation({ leaf = "workspaces",       enabled = true, speed = 4,  bezier = "nothingEase", style = "slidevert" })
hl.animation({ leaf = "workspacesIn",     enabled = true, speed = 4,  bezier = "nothingEase", style = "slidevert" })
hl.animation({ leaf = "workspacesOut",    enabled = true, speed = 4,  bezier = "nothingEase", style = "slidevert" })
hl.animation({ leaf = "specialWorkspace", enabled = true, speed = 4,  bezier = "nothingEase", style = "slidevert" })
hl.animation({ leaf = "layers",           enabled = true, speed = 4,  bezier = "nothingEase", style = "slide" })
