# @managed: hyprlock-theme
$background = rgb(000000)
$surface = rgb(111111)
$inputBg = rgba(111111E6)
$border = rgb(222222)
$borderVisible = rgb(333333)
$textDisplay = rgb(FFFFFF)
$textPrimary = rgb(E8E8E8)
$textSecondary = rgb(999999)
$accent = rgb(D71921)
$error = rgb(D44A4A)
$fontDisplay = Geist
$fontMono = Space Mono
