-- Auto-generated by KeybindingService (Quickshell).
-- Manual edits are overwritten at startup.
-- Emergency fallbacks when Quickshell is not running:

local mainMod = "SUPER"

hl.bind(mainMod .. " + Return", hl.dsp.exec_cmd("kitty"))
hl.bind(mainMod .. " + R",      function() hl.exec_cmd("hyprctl reload") end)

hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(),   { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })
