[general]
bars = 7
framerate = 60
autosens = 1
sensitivity = 150

[input]
method = pipewire

[output]
method = raw
raw_target = /dev/stdout
data_format = ascii
ascii_max_range = 7
channels = mono
mono_option = average

[smoothing]
noise_reduction = 40
monstercat = 1.5
waves = 2